services:
  react-app:
    image: node:23.6.0
    container_name: react_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:3000"
    command: sh -c "yarn install && yarn build && yarn start"
    environment:
      - CHOKIDAR_USEPOLLING=true